version: "3.7"
services:
  lamden_events:
    container_name: lamden_events
    image: lamden
    build:
      context: ./lamden/
      args:
        LAMDEN_TAG: ${LAMDEN_TAG?}
        CONTRACTING_TAG: ${CONTRACTING_TAG?}
    working_dir: /lamden/lamden/nodes
    command: "python events.py -p 17080"
    volumes:
      - ${HOME}/.lamden:/root/.lamden
    ports:
      - 17080:17080
    networks:
      - lamden_network
    logging:
      driver: local
      options:
        max-size: 10m

  lamden_webserver:
    container_name: lamden_webserver
    image: lamden
    depends_on:
      - lamden_events
    working_dir: /lamden/lamden/nodes/masternode
    command: "python webserver.py -p 18080 -ep 17080"
    volumes:
      - ${HOME}/.lamden:/root/.lamden
    environment:
      - LAMDEN_SK=${LAMDEN_SK?}
    ports:
      - 18080:18080
    networks:
      - lamden_network
    logging:
      driver: local
      options:
        max-size: 10m

  lamden_node:
    container_name: lamden_node
    image: lamden
    depends_on:
      - lamden_webserver
    working_dir: /lamden
    command: sh -c "[ -z ${LAMDEN_ROLLBACK} ] && ([ -z ${LAMDEN_BOOTNODES} ] && exec lamden start -d True || exec lamden join -d True) || exec lamden join -d True -rp ${LAMDEN_ROLLBACK}"
    volumes:
      - ${HOME}/constitution.json:/root/constitution.json
      - ${HOME}/genesis_block.json:/root/genesis_block.json
      - ${HOME}/.lamden:/root/.lamden
    environment:
      - LAMDEN_SK=${LAMDEN_SK?}
      - LAMDEN_TAG=${LAMDEN_TAG?}
      - CONTRACTING_TAG=${CONTRACTING_TAG?}
      - LAMDEN_BOOTNODES=${LAMDEN_BOOTNODES}
      - LAMDEN_PRIVATE_NETWORK=${LAMDEN_PRIVATE_NETWORK:-False}
      - LAMDEN_ROLLBACK=${LAMDEN_ROLLBACK:-"-1"}
      - DISABLE_CATCHUP=${DISABLE_CATCHUP:-False}
    ports:
      - 19000:19000
      - 19080:19080
    networks:
      - lamden_network
    logging:
      driver: local
      options:
        max-size: 10m

networks:
  lamden_network:
    name: lamden_network
